"""Task3 / 实验 3-10 contextual-retrieval 学习版：课程 campaign.py，DeepSeek 生成前缀 + 本地 Qwen3-Embedding。

不修改课程代码。两处前置 + 三处注入——
前置：课程仓库不带 document_store.json（原版由需 retrieval 服务的索引脚本生成）。
书方 3-10 已通过战役的 evidence.json 保留了全部 22 个 chunk 的原文与文档标题，
本脚本据此**无损重建** document_store.json（分块与评测集 gold_chunk_id 精确一致；
重建件的 chunk 内容与书方证据逐字节相同，仅容器字段按 load_chunks 的读取形状组装）。
注入：
1. campaign.HERE 重定向 + 复制 campaign.py/compare_retrieval.py/evaluation/document_store.json
   （laws 源文档仍从课程 agentic-rag/laws 读取，CHAPTER 在 import 时已绑定课程目录）；
2. campaign.OpenAI 换 deepseek 关 thinking 工厂（前缀生成的唯一 LLM 调用）；
3. ARK_API_KEY=DeepSeek。pricing 置零（未配置 DeepSeek 价格，成本未计算，课程门槛
   tokens>0 且 cost>=0 仍满足）。

稠密检索用课程默认本地模型 Qwen/Qwen3-Embedding-0.6B（首次运行从 HuggingFace 下载）。
"""
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from types import SimpleNamespace

from dotenv import load_dotenv
from openai import OpenAI

ROOT = Path(__file__).resolve().parents[2]
load_dotenv(ROOT / ".env")
DEEPSEEK_KEY = os.getenv("DEEPSEEK_API_KEY", "")
if not DEEPSEEK_KEY:
    raise SystemExit("DEEPSEEK_API_KEY missing")
CONTEXT_MODEL = "deepseek-flash"
ENDPOINT = "https://api.deepseek.com"
OUT = ROOT / "learning/task3/runs/3-10_contextual_retrieval" / datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
OUT.mkdir(parents=True, exist_ok=False)

SRC = ROOT / "chapter3/contextual-retrieval"
book_run = sorted((SRC / "validation" / "runs").iterdir())[-1]
book_evidence = json.loads((book_run / "evidence.json").read_text())
book_chunks = book_evidence["chunks"]
assert len(book_chunks) == book_evidence["scope"]["chunks"], "book evidence chunk count mismatch"

# --- 前置：从书方证据无损重建 document_store.json --------------------------------
store = {}
for c in book_chunks:
    store[c["chunk_id"]] = {
        "content": c["plain"],
        "metadata": {"doc_title": c["doc_title"], "original_text": c["plain"]},
    }
(OUT / "document_store.json").write_text(json.dumps(store, ensure_ascii=False, indent=2))

# 课程模块
sys.path.insert(0, str(ROOT / "chapter3"))
sys.path.insert(0, str(SRC))
import campaign as ctx_campaign  # noqa: E402

data = {
    "experiment": "3-10 contextual-retrieval learning variant",
    "note": "course campaign reused verbatim, full 22-chunk/15-query scope; context prefixes live-generated by deepseek-flash; dense retrieval with local Qwen/Qwen3-Embedding-0.6B; document_store rebuilt byte-identical in chunk content from the book's passed evidence (store container not shipped in repo)",
    "context_llm": {"provider": "deepseek", "endpoint": ENDPOINT, "model": CONTEXT_MODEL},
    "embedding_model": "Qwen/Qwen3-Embedding-0.6B",
    "document_store_source": {
        "book_run": book_run.name,
        "chunks": len(book_chunks),
        "chunk_sha256": hashlib.sha256(
            json.dumps([{c["chunk_id"]: c["plain"]} for c in book_chunks], ensure_ascii=False, sort_keys=True).encode()
        ).hexdigest(),
    },
    "source_hashes": {
        "chapter3/contextual-retrieval/campaign.py": hashlib.sha256((SRC / "campaign.py").read_bytes()).hexdigest(),
        "chapter3/contextual-retrieval/compare_retrieval.py": hashlib.sha256(
            (SRC / "compare_retrieval.py").read_bytes()
        ).hexdigest(),
    },
}

# --- 注入 1：HERE 重定向 + 数据复制 ----------------------------------------------
shutil.copytree(SRC / "evaluation", OUT / "evaluation")
shutil.copy2(SRC / "campaign.py", OUT / "campaign.py")
shutil.copy2(SRC / "compare_retrieval.py", OUT / "compare_retrieval.py")
ctx_campaign.HERE = OUT

# --- 注入 2：deepseek 关 thinking 工厂 -------------------------------------------
_real_openai = OpenAI


class _NoThinkingCompletions:
    def __init__(self, inner):
        self._inner = inner

    def create(self, **req):
        req.setdefault("extra_body", {})["thinking"] = {"type": "disabled"}
        return self._inner.create(**req)


class _NoThinkingOpenAI:
    def __init__(self, **kwargs):
        inner = _real_openai(**kwargs)
        self.chat = SimpleNamespace(completions=_NoThinkingCompletions(inner.chat.completions))


ctx_campaign.OpenAI = _NoThinkingOpenAI

# --- 注入 3：凭据 + argv ----------------------------------------------------------
os.environ["ARK_API_KEY"] = DEEPSEEK_KEY
sys.argv = [
    "campaign.py",
    "--context-model", CONTEXT_MODEL,
    "--endpoint", ENDPOINT,
    "--workers", "4",
    "--input-price-per-million-usd", "0",
    "--output-price-per-million-usd", "0",
]

print("Output:", OUT, flush=True)
print(f"context LLM={CONTEXT_MODEL} @ deepseek | embedding=Qwen3-Embedding-0.6B (local) | chunks={len(book_chunks)} queries=15", flush=True)
exit_code = ctx_campaign.main()

# --- 学习版证据层 -----------------------------------------------------------------
latest = json.loads((OUT / "validation" / "latest.json").read_text())
run_dir = OUT / "validation/runs" / latest["run_id"]
evidence = json.loads((run_dir / "evidence.json").read_text())

leaked = [
    str(p.relative_to(OUT))
    for p in sorted(OUT.rglob("*"))
    if p.is_file() and DEEPSEEK_KEY in p.read_text(errors="ignore")
]
data["credential_scan_findings"] = leaked
data["course_evidence"] = {
    "status": evidence.get("status"),
    "scope": evidence.get("scope"),
    "acceptance": evidence.get("acceptance"),
    "summary": evidence.get("summary"),
    "configuration": evidence.get("configuration"),
}
data["completed"] = not leaked
payload = json.dumps(data, ensure_ascii=False, indent=2)
assert DEEPSEEK_KEY not in payload
(OUT / "evidence.json").write_text(payload)
(OUT / "evidence.sha256").write_text(
    hashlib.sha256((OUT / "evidence.json").read_bytes()).hexdigest() + "  evidence.json\n"
)
print("\n六方法检索对照（DeepSeek 学习版）", flush=True)
for name, result in (evidence.get("summary", {}).get("methods") or {}).items():
    print(
        f"  {name:<20} MRR={result['mrr']:.3f} "
        f"R@1={result['recall_at_k']['1']:.2f} R@3={result['recall_at_k']['3']:.2f} R@5={result['recall_at_k']['5']:.2f}",
        flush=True,
    )
print("DONE. course status:", evidence.get("status"), "| leak scan:", leaked or "clean", flush=True)
